webrtc: allow configuring timeouts (#3404)
bluenviron/mediamtx pull request #3406
Opened 2024-05-29 13:51 UTC by jwalton

Allow configuration of WebRTC timeouts.

2024-05-29 19:21 UTC, aler9 requested changes
thanks for this patch, take a look at the comment in the review

2024-05-29 19:21 UTC, aler9 commented on internal/core/core.go
in line 853, add a comparison between current and previos WebRTCHandshakeTimeout p.conf.WebRTCTrackGatherTimeout in order to detect changes after a API request or hot reloading

2024-05-30 03:49 UTC, jwalton commented on internal/core/core.go
Fixed.

2024-05-30 11:36 UTC, aler9 approved these changes

2024-05-30 11:36 UTC, merged

2024-05-30 11:37 UTC, aler9 commented
merged, thanks!