Configure the JWT Claim Key for holding MediaMTX Permissions
bluenviron/mediamtx pull request #3560
Opened 2024-07-18 13:38 UTC by izanbard

Why

Solution

Focus on

2024-08-02 08:55 UTC, izanbard commented
@aler9 The test above that has failed is nowhere near the code I have written; passes on my system and is similar to a fail you had yesterday that went away on retry.  Please rerun the check.

2024-08-02 11:09 UTC, izanbard commented
@aler9 thank you

2024-08-04 09:30 UTC, aler9 requested changes
Hello, this feature is useful but you need to perform a couple of changes in order to get the patch merged:
* the permission parsing logic is vulnerable to multiple crashes. In my opinion you should rewrite it entirely by using something like

```go
type customClaims map[string]json.RawMessage
var cc customClaims
_, err = jwt.ParseWithClaims(v["jwt"][0], &cc, keyfunc)
...

rawClaim, ok := cc[m.JWTClaimKey]
if !ok {
   return fmt.Errorf(...)
}

var claim []conf.AuthInternalUserPermission
err := json.Unmarshal(rawClaim, &claim)
if err != nil {
   return err
}

// finally you can use the claim
```
* you need to add the new key to `apidocs/openapi.yaml` too

2024-08-04 09:30 UTC, aler9 commented on internal/auth/manager.go
> +	claims := token.Claims.(jwt.MapClaims)[m.JWTClaimKey].([]interface{})
this is prone to panics since `token.Claims.(jwt.MapClaims)[m.JWTClaimKey]` can be `nil`

2024-08-04 09:30 UTC, aler9 commented on internal/auth/manager.go
> +		MediaMTXPermission.Action = conf.AuthAction(permission.(map[string]interface{})["action"].(string))
this is also a possible cause of panics since permission might not be a `(map[string]interface{})`

2024-08-26 10:41 UTC, aler9 commented
i found a way to implement this feature that is slightly more efficient, since it avoids calling `json.Marshal` and `json.Unmarshal` in series. This has been moved here: #3692

2024-08-26 10:41 UTC, closed without merging